version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    volumes:
      - ./server:/server
    image: s317989/thesis-management-team17:server-tag
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: client.Dockerfile
    volumes:
      - ./client:/client
    image: s317989/thesis-management-team17:client-tag
    ports:
      - "5173:5173"